version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    # Install PyTorch CPU-only first (required for imports)
    - pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
    # Install git prerequisites (LightGlue, RoMa)
    - pip install -r requirements-prereqs.txt
    # Install AquaMVS with dev dependencies (includes Sphinx, Furo, etc.)
    - pip install -e ".[dev]"
    # Build documentation
    - sphinx-build -W -b html docs/ $READTHEDOCS_OUTPUT/html
